---
postgresql_copy:
  - plugins/modules/postgresql_copy.py
  - tests/integration/targets/postgresql_copy/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_db:
  - plugins/modules/postgresql_db.py
  - tests/integration/targets/postgresql_db/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_ext:
  - plugins/modules/postgresql_ext
  - tests/integration/targets/postgresql_ext/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_idx:
  - plugins/modules/postgresql_idx
  - tests/integration/targets/postgresql_idx/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_info:
  - plugins/modules/postgresql_info
  - tests/integration/targets/postgresql_info/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_lang:
  - plugins/modules/postgresql_lang
  - tests/integration/targets/postgresql_lang/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_membership:
  - plugins/modules/postgresql_membership
  - tests/integration/targets/postgresql_membership/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_owner:
  - plugins/modules/postgresql_owner
  - tests/integration/targets/postgresql_owner/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_pg_hba:
  - plugins/modules/postgresql_pg_hba
  - tests/integration/targets/postgresql_pg_hba/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_ping:
  - plugins/modules/postgresql_ping
  - tests/integration/targets/postgresql_ping/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_privs:
  - plugins/modules/postgresql_privs
  - tests/integration/targets/postgresql_privs/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_publication:
  - plugins/modules/postgresql_publication
  - tests/integration/targets/postgresql_publication/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_query:
  - plugins/modules/postgresql_query
  - tests/integration/targets/postgresql_query/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_schema:
  - plugins/modules/postgresql_schema
  - tests/integration/targets/postgresql_schema/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_sequence:
  - plugins/modules/postgresql_sequence
  - tests/integration/targets/postgresql_sequence/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_set:
  - plugins/modules/postgresql_set
  - tests/integration/targets/postgresql_set/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_slot:
  - plugins/modules/postgresql_slot
  - tests/integration/targets/postgresql_slot/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_subscription:
  - plugins/modules/postgresql_subscription
  - tests/integration/targets/postgresql_subscription/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_table:
  - plugins/modules/postgresql_table
  - tests/integration/targets/postgresql_table/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_tablespace:
  - plugins/modules/postgresql_tablespace
  - tests/integration/targets/postgresql_tablespace/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_user:
  - plugins/modules/postgresql_user
  - tests/integration/targets/postgresql_user/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**

postgresql_user_obj_stat_info:
  - plugins/modules/postgresql_user_obj_stat_info
  - tests/integration/targets/postgresql_user_obj_stat_info/**
  - plugins/module_utils/**
  - plugins/doc_fragments/postgres.py
  - tests/integration/targets/setup_*/**
