---
name: Units
on:
  push:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-collection-workflow.yml'
    - '.github/workflows/ansible-test-units.yml'
    - '.github/filters.yml'
  pull_request:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-collection-workflow.yml'
    - '.github/workflows/ansible-test-units.yml'
    - '.github/filters.yml'

jobs:
  sanity:
    uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    with:
      fail-fast: false
      testing-type: units
