---
name: Ansible Collection Workflow
on:
  workflow_call:
    inputs:
      pre-test-cmd:
        description: Parameter for action paths-filter
        default:
        required: false
        type: string
      runs-on:
        description: docker image to run GHA
        default: 'ubuntu-latest'
        type: string
        required: false
      test-deps:
        description: Parameter for ansible-test-gh-action
        default:
        type: string
        required: false
      testing-type:
        description: Parameter for ansible-test-gh-action
        default: integration
        type: string
        required: true

jobs:
  changes:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      targets: ${{ steps.filter.outputs.changes }}
    steps:
    # FIXME For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    # Run change detection to build tests
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: '.github/filters.yml'

  test-python:
    name: "${{ matrix.target }} ${{ matrix.docker-image }} ${{ inputs.extra }} by ${{ matrix.ansible }} running python ${{ matrix.ansible-python }}"
    runs-on: ${{ inputs.runs-on }}
    needs: changes
    strategy:
      matrix:
        # https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs
        ansible-core-version:
        - stable-2.9       # EOL May 2022
        - stable-2.10      # EOL May 2022
        - stable-2.11      # EOL May 2022
        - stable-2.12      # EOL May 2023
        - devel
        python-version:
        - 3.8
        target-python-version:
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        - 2.6

    steps:
    - name: 'ansible-test integration --docker ${{ matrix.docker-image }} (Ansible: ${{ matrix.ansible-core-version }} running python: ${{ matrix.ansible-python }}'
      uses: ansible-community/ansible-test-gh-action@unstable/v1
      with:
        ansible-core-version: ${{ matrix.ansible-core-version }}
        pre-test-cmd: ${{ inputs.pre-test-cmd }}
        python-version: ${{ matrix.python-version }}
        target: ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}
        target-python-version: ${{ matrix.target-python-version }}
        testing-type: ${{ inputs.testing-type }}
        test-deps: ${{ inputs.test-deps }}

  test-docker:
    name: "${{ matrix.target }} ${{ matrix.docker-image }} ${{ inputs.extra }} by ${{ matrix.ansible }} running python ${{ matrix.ansible-python }}"
    runs-on: ${{ inputs.runs-on }}
    needs: changes
    strategy:
      matrix:
        # https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs
        ansible-core-version:
        - stable-2.9       # EOL May 2022
        - stable-2.10      # EOL May 2022
        - stable-2.11      # EOL May 2022
        - stable-2.12      # EOL May 2023
        - devel
        python-version:
        - 3.8
        docker-image:
        - centos6          # python2
        - centos7          # python2
        - opensuse15py2    # python2
        - alpine3          # python3
        - centos8          # python3
        - fedora32         # python3
        - fedora33         # python3
        - opensuse15       # python3
        - ubuntu1804       # python3
        - ubuntu2004       # python3

    steps:
    - name: 'ansible-test integration --docker ${{ matrix.docker-image }} (Ansible: ${{ matrix.ansible-core-version }} running python: ${{ matrix.ansible-python }}'
      uses: ansible-community/ansible-test-gh-action@unstable/v1
      with:
        ansible-core-version: ${{ matrix.ansible-core-version }}
        docker-image: ${{ matrix.docker-image }}
        pre-test-cmd: ${{ inputs.pre-test-cmd }}
        python-version: ${{ matrix.python-version }}
        target: ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}
        testing-type: ${{ inputs.testing-type }}
        test-deps: ${{ inputs.test-deps }}
