---
name: Integration
on:
  push:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-test-plugins.yml'
    - '.github/filters.yml'
    - '.github/**'
  pull_request:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-test-plugins.yml'
    - '.github/filters.yml'

jobs:
  pg-14:
    uses: c2main/ansible-collection-gh-workflow/.github/workflows/workflow.yml@devel
    with:
      fail-fast: false
      pre-test-cmd: >
        ls -al
        && sed -i 's/^pg_version:.*/pg_version: \"14\"/g'
             ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      test-python: false
      testing-type: integration
