---
name: Integration
on:
  push:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-test-plugins.yml'
    - '.github/filters.yml'
    - '.github/**'
  pull_request:
    paths:
    - 'plugins/**'
    - 'tests/**'
    - '.github/workflows/ansible-test-plugins.yml'
    - '.github/filters.yml'

jobs:
  14:
    uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    with:
      fail-fast: false
      pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"14\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      test-python: false
      testing-type: integration



  #ansible-test:
    #name: "My title"
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #test-python: false
      #test-docker: true
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"${{ matrix.postgresql-version }}\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-deps: community.general
      #testing-type: ${{ matrix.testing-type }}
    #strategy:
      #matrix:
        #testing-type:
        #- integration
        #- units
        #- sanity
        #postgresql-version:
        #- 9.6  # EOL November 11, 2021
        #- 10   # EOL November 10, 2022
        #- 11   # EOL November 9,  2023
        #- 12   # EOL November 14, 2024
        #- 13   # EOL November 13, 2025
        #- 14   # EOL November 12, 2026

  #integration-14:
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #fail-fast: false
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"14\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-python: false
      #test-deps: community.general
      #testing-type: integration
  #units-14:
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #fail-fast: false
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"14\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-python: false
      #test-deps: community.general
      #testing-type: units

  #integration-13:
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #fail-fast: false
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"13\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-python: false
      #test-deps: community.general
      #testing-type: integration
  #units-13:
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #fail-fast: false
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"13\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-python: false
      #test-deps: community.general
      #testing-type: units
  #sanity-13:
    #uses: klando/community.postgresql/.github/workflows/ansible-collection-workflow.yml@fix-integration-tests
    #with:
      #fail-fast: false
      #pre-test-cmd: "ls -al && sed -i 's/^pg_version:.*/pg_version: \"13\"/g' ./tests/integration/targets/setup_postgresql_db/defaults/main.yml"
      #test-python: false
      #test-deps: community.general
      #testing-type: sanity
