---
name: Units
on:
  workflow_dispatch:

jobs:
  units:
    uses: c2main/ansible-collection-gh-workflow/.github/workflows/workflow.yml@devel
    with:
      fail-fast: false
      testing-type: units
