---
name: Ansible Collection Workflow
on:
  workflow_call:
    inputs:
      pre-test-cmd:
        description: Parameter for action paths-filter
        default:
        required: false
        type: string
      runs-on:
        description: docker image to run GHA
        default: 'ubuntu-latest'
        type: string
        required: false
      test-deps:
        description: Parameter for ansible-test-gh-action
        default:
        type: string
        required: false
      testing-type:
        description: Parameter for ansible-test-gh-action
        default: integration
        type: string
        required: true

jobs:
  changes:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      targets: ${{ steps.filter.outputs.changes }}
    steps:
    # FIXME For pull requests it's not necessary to checkout the code
    - uses: actions/checkout@v2
    # Run change detection to build tests
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: '.github/filters.yml'

  test-python:
    name: "target-python: ${{ matrix.target-python-version }} | ansible: ${{ matrix.ansible-core-version }} | python: ${{ matrix.python-version }}"
    runs-on: ${{ inputs.runs-on }}
    needs: changes
    strategy:
      matrix:
        # https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs
        ansible-core-version:
        - stable-2.9       # EOL May 2022
        - stable-2.10      # EOL May 2022
        - stable-2.11      # EOL May 2022
        - stable-2.12      # EOL May 2023
        - devel
        python-version:
        - 3.8
        target-python-version:
        - 3.9
        - 3.8
        - 3.7
        - 3.6
        - 3.5
        - 2.7
        - 2.6
        exclude:
        - ansible-core-version: stable-2.9
          target-python-version: 3.9
        - ansible-core-version: stable-2.9
          target-python-version: 3.10
        - ansible-core-version: stable-2.10
          target-python-version: 3.10
        - ansible-core-version: stable-2.11
          target-python-version: 3.10
        - ansible-core-version: devel
          target-python-version: 2.6

    steps:
    - name: "ansible-test ${{ inputs.testing-type }} ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}"
      uses: ansible-community/ansible-test-gh-action@unstable/v1
      with:
        ansible-core-version: ${{ matrix.ansible-core-version }}
        pre-test-cmd: ${{ inputs.pre-test-cmd }}
        python-version: ${{ matrix.python-version }}
        target: ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}
        target-python-version: ${{ matrix.target-python-version }}
        testing-type: ${{ inputs.testing-type }}
        test-deps: ${{ inputs.test-deps }}

  test-docker:
    name: "docker-image: ${{ matrix.docker-image }} | ansible: ${{ matrix.ansible-core-version }} | python: ${{ matrix.python-version }}"
    runs-on: ${{ inputs.runs-on }}
    needs: changes
    strategy:
      matrix:
        # https://docs.ansible.com/ansible/devel/reference_appendices/release_and_maintenance.html#ansible-core-changelogs
        ansible-core-version:
        - stable-2.9       # EOL May 2022
        - stable-2.10      # EOL May 2022
        - stable-2.11      # EOL May 2022
        - stable-2.12      # EOL May 2023
        - devel
        python-version:
        - 3.8
        # devel: https://github.com/ansible/ansible/blob/devel/test/lib/ansible_test/_data/completion/docker.txt
        docker-image:
        - alpine3                        # python 3.9
        - centos6                        # python 2.6
        - centos7                        # python 2.7
        - centos8                        # python 3.6
        - fedora34                       # python 3.9
        - opensuse15py2                  # python 2.7
        - opensuse15                     # python 3.6
        - ubuntu1804                     # python 3.6
        - ubuntu2004                     # python 3.8

        include:
        - ansible-core-version: stable-2.9
          docker-image: fedora30         # python 3.7
        - ansible-core-version: stable-2.9
          docker-image: fedora31         # python 3.7
        - ansible-core-version: stable-2.9
          docker-image: ubuntu1604       # python 2.7
        - ansible-core-version: stable-2.10
          docker-image: fedora30         # python 3.7
        - ansible-core-version: stable-2.10
          docker-image: fedora31         # python 3.7
        - ansible-core-version: stable-2.10
          docker-image: fedora32         # python 3.8
        - ansible-core-version: stable-2.10
          docker-image: ubuntu1604       # python 2.7
        - ansible-core-version: stable-2.11
          docker-image: fedora32         # python 3.8
        - ansible-core-version: stable-2.11
          docker-image: fedora33         # python 3.9
        - ansible-core-version: stable-2.12
          docker-image: centos6          # python 2.6
        - ansible-core-version: stable-2.12
          docker-image: fedora33         # python 3.9
        - ansible-core-version: devel
          docker-image: fedora35         # python 3.10

        exclude:
        - ansible-core-version: 2.9
          docker-image: alpine3
        - ansible-core-version: 2.9
          docker-image: fedora34
        - ansible-core-version: 2.9
          docker-image: ubuntu2004
        - ansible-core-version: 2.10
          docker-image: alpine3
        - ansible-core-version: 2.10
          docker-image: fedora34
        - ansible-core-version: 2.11
          docker-image: fedora34
        - ansible-core-version: devel
          docker-image: centos6
        - ansible-core-version: devel
          docker-image: centos8

    steps:
    - name: "ansible-test ${{ inputs.testing-type }} ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}"
      uses: ansible-community/ansible-test-gh-action@unstable/v1
      with:
        ansible-core-version: ${{ matrix.ansible-core-version }}
        docker-image: ${{ matrix.docker-image }}
        pre-test-cmd: ${{ inputs.pre-test-cmd }}
        python-version: ${{ matrix.python-version }}
        target: ${{ join(fromJSON(needs.changes.outputs.targets), ' ') }}
        testing-type: ${{ inputs.testing-type }}
        test-deps: ${{ inputs.test-deps }}
